apiVersion: 1

datasources:
  - name: VictoriaMetrics
    type: prometheus
    uid: vm
    access: proxy
    url: http://172.21.21.60:8428/prometheus
    isDefault: true
    editable: false
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://172.21.21.6:3100
    isDefault: false
    editable: false
    jsonData:
      maxLines: 1000